### ISSUE TITLE
Upgrade django-recaptcha version

### ISSUE THREAD

**Issue by giopromolla** [volrath/django-captcha-admin#2]
Hi, you should upgrade django-recaptcha version to allow "I'm not a Robot" reCaptcha and HTTPS requests.

**Comment by giopromolla** [comment]
SOLVED

**Comment by ShalbafZadeh** [comment]
@giopromolla Hi is this version released on PyPI?
Thanks

**Comment by giopromolla** [comment]
Hi, yes I'm using django-recaptcha==1.3.0.

**Comment by ShalbafZadeh** [comment]
@giopromolla i followed instructions on README and still getting the old enter captcha value 
![screenshot from 2017-12-09 13-50-34](https://user-images.githubusercontent.com/4537866/33794796-30d1e406-dce8-11e7-93c6-baef333fc737.png)


i'm using python 2.7
 Django 1.9.5 
 django-recaptcha  1.3.0
django-captcha-admin  0.2

 and admin panel is accessable over https

and recatcha admin panel says my site is V2 Type

is any other configuration necessary?

Thanks in advance

**Comment by alireza-ahmadi** [comment]
@giopromolla I have the same issue.

**Comment by giopromolla** [comment]
I have the same config as you, only Django version is different (I'm using Django 1.8.1).

Is your recaptcha configuration ok? V2 I'm not a Robot ?

**Comment by ShalbafZadeh** [comment]
@giopromolla yeah V2 I'm not a Robot
Also tested with django 1.9.5 and issue still happens
is there any setting required for django ?
something like USE_SSL or something else?

**Comment by giopromolla** [comment]
If you run django locally (without https) it works ? 
Can you try using Django 1.8.1? just to be sure that Django version is not the problem.

**Comment by ShalbafZadeh** [comment]
@giopromolla i think new version is not released on PyPI 
https://pypi.python.org/pypi/django-captcha-admin/0.1
PyPI says latest version is 0.1 which is released in 
2014-06-05

**Comment by volrath** [comment]
@ShalbafZadeh Did you try version 0.2 https://pypi.python.org/pypi/django-captcha-admin/0.2 ? -- 2017-06-01

**Comment by ShalbafZadeh** [comment]
i've created a repo using django-recaptcha-admin 0.2 and django 1.8.1 and hard coded a pair V2  recaptcha private and public key and problem still persists

repo address https://github.com/ShalbafZadeh/recaptcha-test

recaptcha panel : 
<img width="960" alt="screen shot 2017-12-24 at 1 00 58 am" src="https://user-images.githubusercontent.com/4537866/34322773-f47db034-e845-11e7-9320-a3066c05f3b6.png">

project admin panel : 
<img width="1033" alt="screen shot 2017-12-24 at 12 53 21 am" src="https://user-images.githubusercontent.com/4537866/34322774-fac3e008-e845-11e7-97f0-5c5a9a03525f.png">

PS : 
@giopromolla @volrath i really appreciate effort of you guys to solve this issue for me
thank you very much

**Comment by giopromolla** [comment]
Hi, can you give me permission to push? I have the solution

**Comment by volrath** [comment]
Can you submit a PR?

**Comment by giopromolla** [comment]
Done!
